name: Get Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Can be dispatched manually

jobs:
  get-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Get contributors
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        run: pnpm crowdin-contributors

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-crowdin-contributors
          branch-suffix: timestamp
          commit-message: Update Crowdin contributors
          base: dev
          title: Update Crowdin contributors
          body: Automated update of Crowdin contributors list
          labels: update 🔄
